<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>StartDown</AssemblyName>
    <RootNamespace>StartDown</RootNamespace>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StartDown.Core\StartDown.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Link="README.md" CopyToPublishDirectory="PreserveNewest" />
    <None Include="..\..\LICENSE" Link="LICENSE" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
