<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\StartDown.Core\StartDown.Core.csproj" />
    <ProjectReference Include="..\..\src\StartDown\StartDown.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\StartDown.WindowFixture\StartDown.WindowFixture.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
